name: Manual build and push

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Create Docker metadata (image tags)
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            sibswiss/training-seq-spatial-transcriptomics-rstudio
          tags: latest

      # 4. Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        shell: bash

      # 5. Cache R package layers (optional but speeds up builds)
      - name: Restore Docker cache
        uses: actions/cache@v3
        with:
          path: /tmp/renv-cache
          key: renv-cache-${{ hashFiles('Docker/renv.lock') }}

      # 6. Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Docker
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
          cache-from: type=gha,scope=renv
          cache-to: type=gha,mode=max,scope=renv
          build-args: |
            NCPUS=4  # GitHub runners have 2 cores
